package com.demo.exceptionhandling;

public class FinallyBlock {
public static void main(String[] args) {
		
		try
		{
			int a=10;
			System.out.println(a/0);
		}
//		catch (Exception e) {
//			
//		}
		finally
		{
			System.out.println("Done...");
		}

		System.out.println("Rest code");
		// catch - auto generated by JVM - abruptly stop
	}

}
